# docker-compose.offline.yml
services:
  # Fragments microservice API server
  fragments:
    # Use a proper init process (tini)
    init: true
    # Build the Docker Image using the Dockerfile
    # and current directory as the build context
    build: .
    # Environment variables to use
    environment:
      # Our API will be running on http://localhost:8080
      - API_URL=http://localhost:8080
      # Use Basic Auth (for running tests, CI)
      - HTPASSWD_FILE=tests/.htpasswd
      # Use the LOG_LEVEL set in the host environment, or default to info
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # AWS Amazon Cognito User Pool ID
      - AWS_COGNITO_POOL_ID=us-east-1_6Y1YuolUi
      # AWS Amazon Cognito Client App ID
      - AWS_COGNITO_CLIENT_ID=1ps43vf9khjlj8060qcn78vcjl
    # Ports to publish
    ports:
      - '8080:8080'
